"""add subscription model

Revision ID: 490b5b6e8946
Revises: ca1290241d43
Create Date: 2026-02-27 13:27:23.677186

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '490b5b6e8946'
down_revision: Union[str, Sequence[str], None] = 'ca1290241d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'purchases',
    sa.Column('amount', sa.Float(), nullable=False, server_default="0")
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'amount')
    # ### end Alembic commands ###
