"""add soft delete to video

Revision ID: d2f78319aaa9
Revises: b7a42c5816b3
Create Date: 2026-02-27 14:41:59.992926

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f78319aaa9'
down_revision: Union[str, Sequence[str], None] = 'b7a42c5816b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'videos',
    sa.Column(
        'is_deleted',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)

op.add_column(
    'videos',
    sa.Column(
        'deleted_at',
        sa.DateTime(),
        nullable=True
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'deleted_at')
    op.drop_column('videos', 'is_deleted')
    # ### end Alembic commands ###
